[2023-01-30T15:49:39.690+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-30T15:49:38.448413+00:00 [queued]>
[2023-01-30T15:49:39.707+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-30T15:49:38.448413+00:00 [queued]>
[2023-01-30T15:49:39.707+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T15:49:39.708+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T15:49:39.709+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T15:49:39.721+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-01-30 15:49:38.448413+00:00
[2023-01-30T15:49:39.730+0000] {standard_task_runner.py:55} INFO - Started process 2763 to run task
[2023-01-30T15:49:39.735+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-01-30T15:49:38.448413+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp0sb5x7_m']
[2023-01-30T15:49:39.740+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask is_api_available
[2023-01-30T15:49:39.965+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-01-30T15:49:38.448413+00:00 [running]> on host 3c28126f9714
[2023-01-30T15:49:40.148+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T15:49:38.448413+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T15:49:38.448413+00:00
[2023-01-30T15:49:40.153+0000] {http.py:120} INFO - Poking: api/
[2023-01-30T15:49:40.189+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-01-30T15:49:40.199+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-01-30T15:49:40.587+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-01-30T15:49:40.603+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230130T154938, start_date=20230130T154939, end_date=20230130T154940
[2023-01-30T15:49:40.651+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-30T15:49:40.683+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
