[2023-01-30T15:26:25.604+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T15:26:25.636+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T15:26:25.639+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T15:26:25.641+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T15:26:25.642+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T15:26:25.674+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-01-29 00:00:00+00:00
[2023-01-30T15:26:25.695+0000] {standard_task_runner.py:55} INFO - Started process 1585 to run task
[2023-01-30T15:26:25.725+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2023-01-29T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp0d6zbwbu']
[2023-01-30T15:26:25.729+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask is_api_available
[2023-01-30T15:26:25.891+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2023-01-29T00:00:00+00:00 [running]> on host 3c28126f9714
[2023-01-30T15:26:26.156+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-29T00:00:00+00:00
[2023-01-30T15:26:26.161+0000] {http.py:120} INFO - Poking: api/
[2023-01-30T15:26:26.185+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-01-30T15:26:26.192+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-01-30T15:26:26.539+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-01-30T15:26:26.553+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230129T000000, start_date=20230130T152625, end_date=20230130T152626
[2023-01-30T15:26:26.614+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-30T15:26:26.646+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-30T16:12:15.064+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T16:12:15.077+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T16:12:15.079+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:15.080+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T16:12:15.081+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:15.100+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-01-29 00:00:00+00:00
[2023-01-30T16:12:15.110+0000] {standard_task_runner.py:55} INFO - Started process 3939 to run task
[2023-01-30T16:12:15.117+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2023-01-29T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpfolopa_c']
[2023-01-30T16:12:15.120+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask is_api_available
[2023-01-30T16:12:15.231+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2023-01-29T00:00:00+00:00 [running]> on host 3c28126f9714
[2023-01-30T16:12:15.343+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-29T00:00:00+00:00
[2023-01-30T16:12:15.346+0000] {http.py:120} INFO - Poking: api/
[2023-01-30T16:12:15.372+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-01-30T16:12:15.376+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-01-30T16:12:15.787+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-01-30T16:12:15.802+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230129T000000, start_date=20230130T161215, end_date=20230130T161215
[2023-01-30T16:12:15.987+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-30T16:12:16.151+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
