[2023-01-30T15:26:25.470+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T15:26:25.493+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T15:26:25.495+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T15:26:25.496+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T15:26:25.497+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T15:26:25.524+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-01-29 00:00:00+00:00
[2023-01-30T15:26:25.537+0000] {standard_task_runner.py:55} INFO - Started process 1582 to run task
[2023-01-30T15:26:25.547+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2023-01-29T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpyxgccut8']
[2023-01-30T15:26:25.554+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask create_table
[2023-01-30T15:26:25.796+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2023-01-29T00:00:00+00:00 [running]> on host 3c28126f9714
[2023-01-30T15:26:25.940+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-29T00:00:00+00:00
[2023-01-30T15:26:25.982+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-01-30T15:26:26.007+0000] {sql.py:315} INFO - Running statement: 
        create table if not exists users(
            firstname text not null, 
            lastname text not null, 
            country text not null, 
            username text not null, 
            password text not null,
            email text not null);
            , parameters: None
[2023-01-30T15:26:26.014+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-01-30T15:26:26.071+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230129T000000, start_date=20230130T152625, end_date=20230130T152626
[2023-01-30T15:26:26.177+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-30T15:26:26.213+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-30T16:12:15.138+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T16:12:15.151+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-01-29T00:00:00+00:00 [queued]>
[2023-01-30T16:12:15.152+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:15.153+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T16:12:15.154+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:15.178+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-01-29 00:00:00+00:00
[2023-01-30T16:12:15.189+0000] {standard_task_runner.py:55} INFO - Started process 3941 to run task
[2023-01-30T16:12:15.199+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2023-01-29T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp82fayrb4']
[2023-01-30T16:12:15.208+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask create_table
[2023-01-30T16:12:15.334+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2023-01-29T00:00:00+00:00 [running]> on host 3c28126f9714
[2023-01-30T16:12:15.419+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-29T00:00:00+00:00
[2023-01-30T16:12:15.432+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-01-30T16:12:15.449+0000] {sql.py:315} INFO - Running statement: 
        create table if not exists users(
            firstname text not null, 
            lastname text not null, 
            country text not null, 
            username text not null, 
            password text not null,
            email text not null);
            , parameters: None
[2023-01-30T16:12:15.451+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-01-30T16:12:15.465+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230129T000000, start_date=20230130T161215, end_date=20230130T161215
[2023-01-30T16:12:15.576+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-30T16:12:15.609+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
